### ISSUE TITLE
NO FILE calc_rahu_ketu_pos

### ISSUE THREAD

**Issue by bezdeneg** [arvindb95/Nakshatra_calculator#1]
Error on line :
>  from calc_rahu_ketu_pos import *
ModuleNotFoundError
No module named 'calc_rahu_ketu_pos'

**Comment by arvindb95** [comment]
Hi @bezdeneg ,

Sorry for the late reply. I just saw this. There is a script called `calc_rahu_ketu_pos.py` in the main directory of this repo. If that file is in the directory that you cloned the main code, it should work. Let me know if this works for you.

Regards
Arvind

**Comment by whiteangelnoor** [comment]
thanks for the great 👍🏽  work. can please add calculating Islamic moon lunar its 90% same naksharta but in islamic its with 28 houses but with naksharta with 27.. we missing correct  calculations  for that, if you help us please

**Comment by arvindb95** [comment]
@bezdeneg Did your problem get resolved? I can close this issue if that is the case.
